"""empty message

Revision ID: 5ffa4dabeffd
Revises: 19ffef529fc4
Create Date: 2022-09-23 16:47:59.714280

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ffa4dabeffd'
down_revision = '19ffef529fc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favorites', 'planet_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('favorites', 'people_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favorites', 'people_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('favorites', 'planet_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
